Implemented server-side utilities and refined client-side utilities

diff --git a/src/peekaygee-push b/src/peekaygee-push
--- a/src/peekaygee-push
+++ b/src/peekaygee-push
@@ -4,7 +4,7 @@ set -e
 
 if [ -z "$D" ]; then
     D="$(dirname "$(readlink -f "$0")")"
-    for libdir in "$D" "$PKG_LIBDIR" /usr/share/peekaygee; do
+    for libdir in "$D" "$PEEKAYGEE_LIBDIR" /usr/lib/peekaygee; do
         if [ -e "$libdir/libpeekaygee.sh" ]; then
             . "$libdir/libpeekaygee.sh"
             lib_loaded=true
@@ -26,7 +26,7 @@ if [ "$lib_rexec_loaded" != "true" ]; then
         || \
         LIBREXEC_DIR=
     fi
-    for libdir in "$LIBREXEC_DIR" "$PKG_LIBDIR" /usr/lib/librexec; do
+    for libdir in "$LIBREXEC_DIR" "$REXEC_LIBDIR" /usr/lib/librexec; do
         if [ -e "$libdir/librexec.sh" ]; then
             . "$libdir/librexec.sh"
             lib_rexec_loaded="true"
@@ -43,6 +43,8 @@ if [ "$lib_rexec_loaded" != "true" ]; then
         exit 10
     fi
 fi
+
+CONFFILE_NAME="peekaygee.json"
 
 
 function echo_push_usage() {
@@ -105,7 +107,7 @@ if [ -z ${REMOTE+x} ]; then
 fi
 
 
-# Check config to make sure remote exists and has peekaygee-archive installed
+# Check config to make sure remote exists
 if ! config_jq -e '.remotes."'$REMOTE'"' >/dev/null; then
     >&2 echo_push_usage
     >&2 echo
@@ -115,12 +117,22 @@ if ! config_jq -e '.remotes."'$REMOTE'"' >/dev/null; then
     exit 8
 fi
 REMOTE_PATH="$(config_jq -r '.remotes."'$REMOTE'".url')"
+
+# Make sure peekaygee-archive is installed
 if ! rexec "$REMOTE_PATH" "command -v peekaygee-archive &>/dev/null"; then
     >&2 echo
     >&2 echo "E: It doesn't look like the remote '$REMOTE' has peekaygee-archive installed. Please"
     >&2 echo "   install peekaygee-archive on the remote before continuing."
     >&2 echo
     exit 11
+fi
+
+# Make sure archive is initialized
+if ! rexec "$REMOTE_PATH" 'peekaygee-archive init "::path::"'; then
+    >&2 echo
+    >&2 echo "E: Couldn't initialize '$REMOTE_PATH'. Can't continue."
+    >&2 echo
+    continue
 fi
 
 
@@ -137,14 +149,20 @@ fi
 
 IFS="%"
 for prf in "$(config_jq -r '.packages | keys | join("%")')"; do
-    prf="$(config_jq '.packages."'$prf'"')"
-    TYPE="$(echo $prf | jq -r '.type')"
-    MATCH="$(echo $prf | jq -r '.match')"
-    VISIBILITY="$(echo $prf | jq -r '.visibility')"
-    OPTIONS="$(echo $prf | jq '.options')"
+    prfconf="$(config_jq '.packages."'$prf'"')"
+    TYPE="$(echo $prfconf | jq -r '.type')"
+    MATCH="$(echo $prfconf | jq -r '.match')"
+    VISIBILITY="$(echo $prfconf | jq -r '.visibility')"
+    OPTIONS="$(echo $prfconf | jq '.options')"
 
     if [ "$VISIBILITY" == "null" ]; then
-        VISIBILITY=
+        VISIBILITY=public
+    elif [ "$VISIBILITY" != "public" ] && [ "$VISIBILITY" != "private" ]; then
+        >&2 echo
+        >&2 echo "E: Unrecognized visibility: '$VISIBILITY'. Should be 'public' or 'private'. Skipping"
+        >&2 echo "   $prf files."
+        >&2 echo
+        continue
     fi
     if [ "$OPTIONS" == "null" ]; then
         OPTIONS="{}"
@@ -160,13 +178,13 @@ for prf in "$(config_jq -r '.packages | keys | join("%")')"; do
         done < <(find "$d" -type f | egrep "$MATCH")
     done
 
-    echo "Type: $TYPE"
-    echo "Match: $MATCH"
-    echo "Visibility: $VISIBILITY"
-    echo "Options: $OPTIONS"
-    echo "Packages: ${PKGS[@]}"
+    #echo "Type: $TYPE"
+    #echo "Match: $MATCH"
+    #echo "Visibility: $VISIBILITY"
+    #echo "Options: $OPTIONS"
+    #echo "Packages: ${PKGS[@]}"
 
-    if ! rexec "$REMOTE_PATH" "peekaygee-archive supports '$TYPE'"; then
+    if ! rexec "$REMOTE_PATH" "peekaygee-archive supports '$TYPE'" >/dev/null; then
         >&2 echo
         >&2 echo "E: Remote '$REMOTE' doesn't support archive type '$TYPE'. Skipping the following packages:"
         >&2 echo
@@ -174,6 +192,16 @@ for prf in "$(config_jq -r '.packages | keys | join("%")')"; do
         >&2 echo
         continue
     fi
+
+    if ! rsync ${PKGS[@]} "$REMOTE_PATH/incoming/$VISIBILITY/"; then
+        >&2 echo
+        >&2 echo "E: Couldn't push packages to remote '$REMOTE' at '$REMOTE_PATH'"
+        >&2 echo
+        continue
+    fi
 done
 unset IFS
+
+# Now that all packages have been uploaded, update the archive
+rexec "$REMOTE_PATH" 'peekaygee-archive update "::path::"'
 
diff --git a/src/peekaygee-srvworker-apt b/src/peekaygee-srvworker-apt
--- a/src/peekaygee-srvworker-apt
+++ b/src/peekaygee-srvworker-apt
@@ -4,8 +4,8 @@ set -e
 
 D="$(dirname "$(readlink -f "$0")")"
 for libdir in "$D" "$PEEKAYGEE_LIBDIR" /usr/lib/peekaygee; do
-    if [ -e "$libdir/libpeekaygee.sh" ]; then
-        . "$libdir/libpeekaygee.sh"
+    if [ -e "$libdir/libpeekaygee-srvworker.sh" ]; then
+        . "$libdir/libpeekaygee-srvworker.sh"
         lib_loaded=true
         break
     fi
@@ -26,23 +26,17 @@ function echo_usage() {
     echo "      $(basename "$0") [command] [command-options]"
     echo
     echo "DESCRIPTION"
-    echo "      \`peekaygee\` is the client program for the \`peekaygee\` package archive maintenance"
-    echo "      system. It is to be used on build machines to push built packages to remote archives"
-    echo "      for publication."
+    echo "      \`peekaygee-srvworker-apt\` is a \`peekaygee\` server-side worker program that handles archive"
+    echo "      maintenance tasks for apt package archives."
     echo
     echo "COMMANDS"
-    echo "      list [remote] ([pkg-spec])"
-    echo "          List all packages available on [remote], optionally filtered by [pkg-spec]"
+    echo "      add [archive-path] [debfile] [json-options-str]"
+    echo "          Adds package file [debfile] to the peekaygee archive at [archive-path], using [json-options-str]"
+    echo "          to determine certain characteristics"
     echo
-    echo "      push [remote]"
-    echo "          Push all packages matching configured package definitions to [remote]"
-    echo
-    echo "      delete [remote] [pkg-spec]"
-    echo "          Delete all packages matching [pkg-spec] on [remote]"
-    echo
-    echo "      prune [remote ([pkg-spec]) [num-versions]"
-    echo "          Delete all older versions of packages on [remote], optionally matching"
-    echo "          [pkg-spec], saving the most recent [num-versions] versions"
+    echo "      remove [archive-path] [pkg-spec] [json-options-str]"
+    echo "          removes all packages matching [pkg-spec] from the peekaygee archive at [archive-path], using"
+    echo "          [json-options-str] to determine certain characteristics"
     echo
     echo "GLOBAL OPTIONS"
     echo "      -h|--help"
@@ -59,7 +53,7 @@ function echo_usage() {
 # Initial loop to gather global options and main command
 while [ "$#" -gt 0 ]; do
     case "$1" in
-        push|delete|prune|list)
+        add|remove)
             COMMAND="$1"
             shift
             break
@@ -91,6 +85,15 @@ while [ "$#" -gt 0 ]; do
 done
 
 
+# Validate dependencies
+if ! command -v reprepro &>/dev/null; then
+    >&2 echo
+    >&2 echo "E: Required dependency reprepro appears to be missing. Can't continue."
+    >&2 echo
+    exit 19
+fi
+
+
 # Validate empties
 if [ -z ${COMMAND+x} ]; then
     >&2 echo_usage
@@ -102,21 +105,29 @@ fi
 
 
 
-# Run subcommand
+# Execute subcommand logic
 
-# See if it's local
-CMD="$D/peekaygee-$COMMAND"
-if [ ! -x "$CMD" ]; then
-    # Otherwise, see if it's on the path
-    if ! CMD="$(command -v "peekaygee-$COMMAND")"; then
+ARCHIVE_TYPE=apt
+
+if [ "$COMMAND" == "add" ]; then
+    # Defines ARCHIVE, DEBFILE, OPTIONS, and TARG_ARCHIVE, and throws appropriate errors
+    peekaygee_prep_srvworker_add
+
+    if [ ! -e "$TARG_ARCHIVE/conf/distributions" ]; then
         >&2 echo
-        >&2 echo "E: Couldn't find subcommand peekaygee-$COMMAND! Are you sure peekaygee"
-        >&2 echo "   is properly installed?"
+        >&2 echo "E: It looks like you haven't yet configured your reprepro archive at '$TARG_ARCHIVE'."
+        >&2 echo "   You must configure this archive by creating a \`distributions\` file at"
+        >&2 echo "   '$TARG_ARCHIVE/conf/distributions'"
         >&2 echo
-        exit 4
+        exit 21
     fi
-fi
 
-"$CMD" $@
+    >&2 echo "E: Not yet implemented"
+    exit 507
+
+elif [ "$COMMAND" == "remove" ]; then
+    >&2 echo "E: Not yet implemented"
+    exit 507
+fi
 
 
